config/routes.rb
Rails.application.routes.draw do
  get 'emails' => "emails#index"

  post 'emails/standard'

  post 'emails/delayed'

  resources :letters,only: [:index] do
    member do
      patch :upvote
      patch :downvote
    end
  end
  root to: 'letters#index'

end

app/models/letter.rb
require "letter_redis_repository"
class Letter < ActiveRecord::Base
   def self.top_10
    ids= LetterRedisRepository.top
    where(id: ids).order(scroe: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def index

  end

  def standard
    SendEmail.default_email(recipients).deliver

    AnotherEmail.default_email(recipients).deliver
    redirect_to emails_path, notice: "Send email standard"
  end

  def delayed
    SendEmailWorker.perform_async("SendEmail",recipients)

    SendEmailWorker.perform_async("AnotherEmail",recipients)

    redirect_to emails_path, notice: "Send email delayed"
  end
  private
  def recipients
    ["shkldon0@gmail.com"]
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def index
    @letters=Letter.all
  end
  def upvote
    @letter=Letter.find params[:id]
    @letter.update_attribute :scroe , @letter.scroe+1
    LetterRedisRepository.increament @letter
    MessageWorker.perform_async "Anonymous", <<EOF, letters_url
The letter #{@letter.name} has been upvoted.
EOF
   
    redirect_to  letters_path,notice: "upvotedd"
  end
  def downvote
    @letter=Letter.find params[:id]
    @letter.update_attribute :scroe , @letter.scroe-1
    LetterRedisRepository.decreament @letter
    MessageWorker.perform_async "Anonymous", <<EOF, letters_url
The letter #{@letter.name} has been downvoted.
EOF
    redirect_to  letters_path,notice: "downvotedd"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def top_letter_cache 
    "top-leeters/"+ Letter.maximum(:updated_at).to_i.to_s
  end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/views/another_email/default_email.html.haml
hi!

app/views/application/_top.html.haml
%h2 Top 10

%ol 
 -Letter.top_10.each do |letter|
  %li
   =letter.name
   %small=letter.scroe
   =link_to raw("&#x25B2;"),upvote_letter_path(letter),method: :patch
   =link_to raw("&#x25BC;"),downvote_letter_path(letter),method: :patch

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redisapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/letters/index.html.haml
%h1 Letters

.col-md-9
 %ul
  -@letters.each do | letter|
   %li
    =letter.name
    %small=letter.scroe

.col-md.3
 =render "top"
   
 

app/views/send_email/default_email.html.haml
hi!